service: compressed-image


provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::compressed-image/*';
functions:
  resize:
    handler: handler.call
    environment:
      BUCKET: compressed-image
      REGION: us-west-2
    events:
      - http:
          path: /{size}/{image}
          method: get
resources:
  Resources:
    ResizedImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: compressed-image
plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: "non-linux"
